from vector import Vector

vector = Vector(5)
print(vector)
vector = Vector((10, 15))
print(vector)
# vector = Vector((10, 15, 0))
vector = Vector(range(2, 10, 2))
print(vector)
vector2 = Vector([0.0, 1.0, 2.0, 3.0])
print(vector2)
# vector = Vector("string")
print(vector + vector2)
# print(1 + vector)
# print(vector + 1)
print(vector - vector2)
# print(1 - vector)
# print(vector - 1)
# print(vector / vector2)
# print(2 / vector)
print(vector / 4)
print(vector * vector2)
print(2 * vector)
print(vector * 2)
